[package]
name = "reverything-core"
description = "NTFS indexing, search and live updates"
version.workspace = true
edition.workspace = true
license = "MIT"

[dependencies]
eyre.workspace = true
rayon.workspace = true
memchr.workspace = true
log.workspace = true
tracing.workspace = true
chrono = { version = "0.4.45", default-features = false, features = ["clock"] }
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_Ioctl",
    "Win32_System_Memory",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
] }
zstd = { version = "0.14.0", default-features = false }
