[package]
name = "reverything-ui"
description = "Reverything search window"
version.workspace = true
edition.workspace = true
build = "build.rs"

[[bin]]
name = "reverything"
path = "src/main.rs"

[dependencies]
reverything-protocol.workspace = true
gpui-kit = "=0.7.0"
image = { version = "0.25", default-features = false }
raw-window-handle = "0.6.2"
tray-icon = "0.26.0"
global-hotkey = "0.8.0"
async-channel = "2.5.0"
serde.workspace = true
serde_json.workspace = true
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_System_Com",
    "Win32_System_Ole",
    "Win32_Storage_FileSystem",
    "Win32_System_Registry",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
    "Win32_System_Time",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
    "Win32_UI_WindowsAndMessaging",
] }

[build-dependencies]
embed-resource = "3.0.11"
